import { ClassCategory, ClassData } from "../types/class.dto"

import {
  BarbellSvg,
  FlexibilitySvg,
  PersonArmsSpreadSvg,
  MindBodySvg,
  RecoverySvg,
  PersonSimpleRunSvg,
} from "@/shared/components/Svg"
import React from "react"

// Sample categories data
export const categories: ClassCategory[] = [
  {
    id: "cardio",
    name: "Cardio Workouts",
    icon: <PersonSimpleRunSvg height="20" width="20" color="#4D5260" />,
    bgColor: "bg-blue",
  },
  {
    id: "strength",
    name: "Strength Training",
    icon: <BarbellSvg height="20" width="20" color="#4D5260" />,
    bgColor: "bg-blue-light",
  },
  {
    id: "flexibility",
    name: "Flexibility & Mobility",
    icon: <FlexibilitySvg height="20" width="20" color="#4D5260" />,
    bgColor: "bg-green",
  },
  {
    id: "core",
    name: "Core Training",
    icon: <PersonArmsSpreadSvg height="20" width="20" color="#4D5260" />,
    bgColor: "bg-green-light",
  },
  {
    id: "mind",
    name: "Mind & Body",
    icon: <MindBodySvg height="20" width="20" color="#4D5260" />,
    bgColor: "bg-yellow",
  },
  {
    id: "recovery",
    name: "Recovery & Relaxation",
    icon: <RecoverySvg height="20" width="20" color="#4D5260" />,
    bgColor: "bg-yellow-light",
  },
]

// Sample time slots
export const timeSlots = [
  "06:00 AM",
  "07:00 AM",
  "08:00 AM",
  "09:00 AM",
  "10:00 AM",
  "11:00 AM",
  "12:00 PM",
  "01:00 PM",
  "02:00 PM",
  "03:00 PM",
  "04:00 PM",
  "05:00 PM",
  "06:00 PM",
  "07:00 PM",
  "08:00 PM",
  "09:00 PM",
  "10:00 PM",
  "11:00 PM",
  "12:00 AM",
]

// Sample class data
export const classes: ClassData[] = [
  {
    id: 1,
    name: "Functional Strength",
    time: "6:30 AM",
    day: "Monday",
    trainer: "Jordan Reed",
    categoryId: "strength",
    duration: "45 minutes",
    level: "Intermediate",
    participants: 12,
    description: "Build functional strength with compound movements and progressive overload techniques.",
  },
  {
    id: 2,
    name: "HIIT Power Session",
    time: "6:00 AM",
    day: "Wednesday",
    trainer: "Chris Williams",
    categoryId: "cardio",
    duration: "30 minutes",
    level: "Advanced",
    participants: 10,
    description:
      "High-intensity interval training designed to maximize calorie burn and improve cardiovascular fitness.",
  },
  {
    id: 3,
    name: "Advanced HIIT",
    time: "7:00 AM",
    day: "Thursday",
    trainer: "Chris Williams",
    categoryId: "cardio",
    duration: "45 minutes",
    level: "Advanced",
    participants: 8,
    description: "Take your HIIT training to the next level with complex movement patterns and minimal rest periods.",
  },
  {
    id: 4,
    name: "Core Stability",
    time: "9:00 AM",
    day: "Tuesday",
    trainer: "Alex Morgan",
    categoryId: "core",
    duration: "45 minutes",
    level: "All Levels",
    participants: 15,
    description:
      "Focus on building a strong and stable core with a variety of planks, anti-rotation exercises, and more.",
  },
  {
    id: 5,
    name: "Functional Core",
    time: "8:00 AM",
    day: "Friday",
    trainer: "Alex Morgan",
    categoryId: "core",
    duration: "30 minutes",
    level: "Intermediate",
    participants: 12,
    description: "Develop core strength that translates to everyday movements and athletic performance.",
  },
  {
    id: 6,
    name: "Strength Circuit",
    time: "12:00 PM",
    day: "Monday",
    trainer: "Jordan Reed",
    categoryId: "strength",
    duration: "60 minutes",
    level: "Intermediate",
    participants: 10,
    description: "Move through a series of strength-building stations targeting all major muscle groups.",
  },
  {
    id: 7,
    name: "Full-Body Strength",
    time: "11:00 AM",
    day: "Wednesday",
    trainer: "Jordan Reed",
    categoryId: "strength",
    duration: "60 minutes",
    level: "Intermediate",
    participants: 15,
    description: "A comprehensive strength workout targeting all major muscle groups for balanced development.",
  },
  {
    id: 8,
    name: "Lower Body Strength",
    time: "1:00 PM",
    day: "Thursday",
    trainer: "Jordan Reed",
    categoryId: "strength",
    duration: "45 minutes",
    level: "All Levels",
    participants: 12,
    description: "Focus on building strength in the legs, glutes, and lower back with targeted exercises.",
  },
  {
    id: 9,
    name: "Pilates Stretch",
    time: "5:00 PM",
    day: "Tuesday",
    trainer: "Sarah Lee",
    categoryId: "flexibility",
    duration: "45 minutes",
    level: "All Levels",
    participants: 15,
    description: "Improve flexibility and posture with controlled, flowing movements inspired by Pilates.",
  },
  {
    id: 10,
    name: "Yoga Flow",
    time: "7:00 PM",
    day: "Monday",
    trainer: "Sarah Lee",
    categoryId: "flexibility",
    duration: "60 minutes",
    level: "All Levels",
    participants: 20,
    description: "A flowing sequence of yoga poses that build strength, flexibility, and mindfulness.",
  },
  {
    id: 11,
    name: "Gentle Yoga",
    time: "7:00 PM",
    day: "Thursday",
    trainer: "Sarah Lee",
    categoryId: "recovery",
    duration: "60 minutes",
    level: "Beginner",
    participants: 15,
    description: "A gentle approach to yoga focusing on relaxation, stress reduction, and gentle stretching.",
  },
  {
    id: 12,
    name: "Mindfulness Meditation",
    time: "7:15 PM",
    day: "Wednesday",
    trainer: "Emily Thompson",
    categoryId: "mind",
    duration: "30 minutes",
    level: "All Levels",
    participants: 10,
    description: "Guided meditation sessions to reduce stress, improve focus, and promote overall wellbeing.",
  },
  {
    id: 13,
    name: "Breathwork & Meditation",
    time: "6:00 PM",
    day: "Friday",
    trainer: "Emily Thompson",
    categoryId: "mind",
    duration: "45 minutes",
    level: "All Levels",
    participants: 12,
    description: "Learn breathing techniques and meditation practices to calm the mind and reduce anxiety.",
  },
  {
    id: 14,
    name: "Weekend Warrior",
    time: "9:00 AM",
    day: "Saturday",
    trainer: "Chris Williams",
    categoryId: "cardio",
    duration: "60 minutes",
    level: "Advanced",
    participants: 15,
    description: "A high-intensity cardio workout to kickstart your weekend and boost your metabolism.",
  },
  {
    id: 15,
    name: "Weekend Yoga",
    time: "10:30 AM",
    day: "Sunday",
    trainer: "Sarah Lee",
    categoryId: "flexibility",
    duration: "60 minutes",
    level: "All Levels",
    participants: 20,
    description: "A relaxing yoga practice to unwind and prepare for the week ahead.",
  },
  {
    id: 16,
    name: "Recovery Yoga",
    time: "6:00 PM",
    day: "Sunday",
    trainer: "Sarah Lee",
    categoryId: "recovery",
    duration: "45 minutes",
    level: "All Levels",
    participants: 15,
    description: "A gentle yoga practice focused on restorative poses and deep relaxation.",
  }
]

