import { IExercise } from '@/shared/types'

export const exercisesDummyData: IExercise[] = [
  {
    id: 1,
    title: 'Bench Press',
    description: 'A classic upper body exercise targeting the chest, shoulders, and triceps.',
    exerciseIconUrl: '/images/barbell.jpg',
    exerciseGifUrl: '/gifs/bench_press.gif',
    caloriePerRound: 50,
  },
  {
    id: 2,
    title: 'Squat',
    description: 'A fundamental lower-body movement that targets the quads, hamstrings, and glutes.',
    exerciseIconUrl: '/images/barbell.jpg',
    exerciseGifUrl: '/gifs/squat.gif',
    caloriePerRound: 60,
  },
  {
    id: 3,
    title: 'Deadlift',
    description: 'A full-body compound exercise primarily working the posterior chain.',
    exerciseIconUrl: '/images/barbell.jpg',
    exerciseGifUrl: '/gifs/deadlift.gif',
    caloriePerRound: 70,
  },
  {
    id: 4,
    title: 'Overhead Press',
    description: 'An upper-body exercise focusing on shoulder and triceps strength.',
    exerciseIconUrl: '/images/barbell.jpg',
    exerciseGifUrl: '/gifs/overhead_press.gif',
    caloriePerRound: 40,
  },
  {
    id: 5,
    title: 'Barbell Row',
    description: 'A back exercise that strengthens the lats and traps.',
    exerciseIconUrl: '/images/barbell.jpg',
    exerciseGifUrl: '/gifs/barbell_row.gif',
    caloriePerRound: 55,
  },
  {
    id: 6,
    title: 'Lunges',
    description: 'A single-leg exercise that works the quads, hamstrings, and glutes.',
    exerciseIconUrl: '/images/barbell.jpg',
    exerciseGifUrl: '/gifs/lunges.gif',
    caloriePerRound: 45,
  },
  {
    id: 7,
    title: 'Bicep Curl',
    description: 'An isolation exercise focusing on the biceps.',
    exerciseIconUrl: '/images/barbell.jpg',
    exerciseGifUrl: '/gifs/bicep_curl.gif',
    caloriePerRound: 30,
  },
  {
    id: 8,
    title: 'Tricep Dips',
    description: 'A bodyweight or weighted exercise targeting the triceps.',
    exerciseIconUrl: '/images/barbell.jpg',
    exerciseGifUrl: '/gifs/tricep_dips.gif',
    caloriePerRound: 35,
  },
  {
    id: 9,
    title: 'Pull-Ups',
    description: 'A bodyweight exercise that strengthens the back and biceps.',
    exerciseIconUrl: '/images/barbell.jpg',
    exerciseGifUrl: '/gifs/pull_ups.gif',
    caloriePerRound: 50,
  },
  {
    id: 10,
    title: 'Leg Press',
    description: 'A machine-based lower-body exercise targeting the quads and glutes.',
    exerciseIconUrl: '/images/barbell.jpg',
    exerciseGifUrl: '/gifs/leg_press.gif',
    caloriePerRound: 55,
  },
  {
    id: 11,
    title: 'Calf Raises',
    description: 'An isolation exercise for strengthening the calf muscles.',
    exerciseIconUrl: '/images/barbell.jpg',
    exerciseGifUrl: '/gifs/calf_raises.gif',
    caloriePerRound: 25,
  },
  {
    id: 12,
    title: 'Plank',
    description: 'A core-strengthening isometric exercise.',
    exerciseIconUrl: '/images/barbell.jpg',
    exerciseGifUrl: '/gifs/plank.gif',
    caloriePerRound: 20,
  },
  {
    id: 13,
    title: 'Russian Twists',
    description: 'An abdominal exercise focusing on obliques and rotational movement.',
    exerciseIconUrl: '/images/barbell.jpg',
    exerciseGifUrl: '/gifs/russian_twist.gif',
    caloriePerRound: 30,
  },
  {
    id: 14,
    title: 'Jump Squats',
    description: 'A plyometric exercise combining squats with explosive jumping.',
    exerciseIconUrl: '/images/barbell.jpg',
    exerciseGifUrl: '/gifs/jump_squats.gif',
    caloriePerRound: 45,
  },
  {
    id: 15,
    title: 'Battle Ropes',
    description: 'A high-intensity cardio and strength exercise.',
    exerciseIconUrl: '/images/barbell.jpg',
    exerciseGifUrl: '/gifs/battle_ropes.gif',
    caloriePerRound: 65,
  },
  {
    id: 16,
    title: 'Kettlebell Swings',
    description: 'A dynamic full-body movement improving strength and endurance.',
    exerciseIconUrl: '/images/barbell.jpg',
    exerciseGifUrl: '/gifs/kettlebell_swing.gif',
    caloriePerRound: 55,
  },
  {
    id: 17,
    title: 'Burpees',
    description: 'A full-body movement that enhances cardiovascular endurance.',
    exerciseIconUrl: '/images/barbell.jpg',
    exerciseGifUrl: '/gifs/burpees.gif',
    caloriePerRound: 70,
  },
  {
    id: 18,
    title: 'Mountain Climbers',
    description: 'A fast-paced core and cardio exercise.',
    exerciseIconUrl: '/images/barbell.jpg',
    exerciseGifUrl: '/gifs/mountain_climbers.gif',
    caloriePerRound: 40,
  },
  {
    id: 19,
    title: 'Box Jumps',
    description: 'A plyometric exercise that builds explosive power.',
    exerciseIconUrl: '/images/barbell.jpg',
    exerciseGifUrl: '/gifs/box_jumps.gif',
    caloriePerRound: 50,
  },
  {
    id: 20,
    title: 'Farmers Walk',
    description: 'A grip and core-strengthening exercise involving carrying heavy weights.',
    exerciseIconUrl: '/images/barbell.jpg',
    exerciseGifUrl: '/gifs/farmers_walk.gif',
    caloriePerRound: 60,
  }
]
