import { ISession } from "@/features/sessions/types";

export const sessionsDummyData: ISession[] = [
  {
    title: "Yoga Basics",
    startDate: "2025-01-15T08:00:00Z",
    duration: 60,
    coachId: 1,
    coachFullname: "John Doe",
    goal: "Flexibility & Balance",
    level: "Beginner",
    description: "A session for beginners to learn the basics of yoga.",
    bannerImageUrl: "",
    totalParticipantNumber: 20,
    currentParticipantNumber: 5,
    price: 15.0,
    equipments: ["Yoga mat"],
    meetingId: "meeting-101"
  },
  {
    title: "Advanced Cardio Blast",
    startDate: "2025-01-16T10:00:00Z",
    duration: 45,
    coachId: 2,
    coachFullname: "Jane Smith",
    goal: "Cardio Workouts",
    level: "Advanced",
    description: "High-intensity cardio session to get your heart pumping.",
    bannerImageUrl: "",
    totalParticipantNumber: 30,
    currentParticipantNumber: 10,
    price: 20.0,
    equipments: ["Towel", "Water bottle"],
    meetingId: "meeting-102"
  },
  {
    title: "Strength Training 101",
    startDate: "2025-01-17T09:00:00Z",
    duration: 90,
    coachId: 3,
    coachFullname: "Mike Johnson",
    goal: "Strength Training",
    level: "Intermediate",
    description: "Learn the basics of strength training and proper form.",
    bannerImageUrl: "",
    totalParticipantNumber: 15,
    currentParticipantNumber: 8,
    price: 25.0,
    equipments: ["Dumbbells"],
    meetingId: "meeting-103"
  },
  {
    title: "Pilates for Core Strength",
    startDate: "2025-01-18T07:30:00Z",
    duration: 50,
    coachId: 4,
    coachFullname: "Emily Davis",
    goal: "Core Training",
    level: "Beginner",
    description: "Build a strong core with beginner-friendly Pilates exercises.",
    bannerImageUrl: "",
    totalParticipantNumber: 25,
    currentParticipantNumber: 12,
    price: 18.0,
    equipments: ["Yoga mat"],
    meetingId: "meeting-104"
  },
  {
    title: "Mindful Meditation",
    startDate: "2025-01-18T19:00:00Z",
    duration: 30,
    coachId: 5,
    coachFullname: "Sophia Lee",
    goal: "Mind and Body",
    level: "All Levels",
    description: "Relax and rejuvenate with guided meditation techniques.",
    bannerImageUrl: "",
    totalParticipantNumber: 10,
    currentParticipantNumber: 3,
    price: 10.0,
    equipments: ["Cushion"],
    meetingId: "meeting-105"
  },
  {
    title: "HIIT Express",
    startDate: "2025-01-19T06:30:00Z",
    duration: 30,
    coachId: 6,
    coachFullname: "David Brown",
    goal: "Cardio Workouts",
    level: "Intermediate",
    description: "A quick and effective high-intensity interval training session.",
    bannerImageUrl: "",
    totalParticipantNumber: 20,
    currentParticipantNumber: 15,
    price: 12.0,
    equipments: ["Towel", "Water bottle"],
    meetingId: "meeting-106"
  },
  {
    title: "Balance and Stability",
    startDate: "2025-01-19T14:00:00Z",
    duration: 60,
    coachId: 7,
    coachFullname: "Angela White",
    goal: "Flexibility & Balance",
    level: "All Levels",
    description: "Improve balance and stability with focused exercises.",
    bannerImageUrl: "",
    totalParticipantNumber: 15,
    currentParticipantNumber: 6,
    price: 14.0,
    equipments: ["Resistance band"],
    meetingId: "meeting-107"
  },
  {
    title: "Power Yoga",
    startDate: "2025-01-20T09:00:00Z",
    duration: 75,
    coachId: 8,
    coachFullname: "Liam Johnson",
    goal: "Mind and Body",
    level: "Advanced",
    description: "An intense yoga session to challenge your mind and body.",
    bannerImageUrl: "",
    totalParticipantNumber: 25,
    currentParticipantNumber: 18,
    price: 22.0,
    equipments: ["Yoga mat"],
    meetingId: "meeting-108"
  },
  {
    title: "Strength Circuit",
    startDate: "2025-01-20T18:00:00Z",
    duration: 40,
    coachId: 9,
    coachFullname: "Olivia Carter",
    goal: "Strength Training",
    level: "Intermediate",
    description: "Full-body circuit training to build strength and endurance.",
    bannerImageUrl: "",
    totalParticipantNumber: 20,
    currentParticipantNumber: 12,
    price: 20.0,
    equipments: ["Dumbbells", "Resistance band"],
    meetingId: "meeting-109"
  },
  {
    title: "Cardio Dance Party",
    startDate: "2025-01-21T11:00:00Z",
    duration: 50,
    coachId: 10,
    coachFullname: "Chris Martin",
    goal: "Cardio Workouts",
    level: "Beginner",
    description: "Get your heart rate up with a fun and energetic dance workout.",
    bannerImageUrl: "",
    totalParticipantNumber: 30,
    currentParticipantNumber: 25,
    price: 18.0,
    equipments: ["Comfortable shoes"],
    meetingId: "meeting-110"
  },
  {
    title: "HIIT Express",
    startDate: "2025-01-19T06:30:00Z",
    duration: 30,
    coachId: 6,
    coachFullname: "David Brown",
    goal: "Cardio Workouts",
    level: "Intermediate",
    description: "A quick and effective high-intensity interval training session.",
    bannerImageUrl: "",
    totalParticipantNumber: 20,
    currentParticipantNumber: 15,
    price: 12.0,
    equipments: ["Towel", "Water bottle"],
    meetingId: "meeting-106"
  },
  {
    title: "Balance and Stability",
    startDate: "2025-01-19T14:00:00Z",
    duration: 60,
    coachId: 7,
    coachFullname: "Angela White",
    goal: "Flexibility & Balance",
    level: "All Levels",
    description: "Improve balance and stability with focused exercises.",
    bannerImageUrl: "",
    totalParticipantNumber: 15,
    currentParticipantNumber: 6,
    price: 14.0,
    equipments: ["Resistance band"],
    meetingId: "meeting-107"
  },
  {
    title: "Power Yoga",
    startDate: "2025-01-20T09:00:00Z",
    duration: 75,
    coachId: 8,
    coachFullname: "Liam Johnson",
    goal: "Mind and Body",
    level: "Advanced",
    description: "An intense yoga session to challenge your mind and body.",
    bannerImageUrl: "",
    totalParticipantNumber: 25,
    currentParticipantNumber: 18,
    price: 22.0,
    equipments: ["Yoga mat"],
    meetingId: "meeting-108"
  },
  {
    title: "Strength Circuit",
    startDate: "2025-01-20T18:00:00Z",
    duration: 40,
    coachId: 9,
    coachFullname: "Olivia Carter",
    goal: "Strength Training",
    level: "Intermediate",
    description: "Full-body circuit training to build strength and endurance.",
    bannerImageUrl: "",
    totalParticipantNumber: 20,
    currentParticipantNumber: 12,
    price: 20.0,
    equipments: ["Dumbbells", "Resistance band"],
    meetingId: "meeting-109"
  },
  {
    title: "Cardio Dance Party",
    startDate: "2025-01-21T11:00:00Z",
    duration: 50,
    coachId: 10,
    coachFullname: "Chris Martin",
    goal: "Cardio Workouts",
    level: "Beginner",
    description: "Get your heart rate up with a fun and energetic dance workout.",
    bannerImageUrl: "",
    totalParticipantNumber: 30,
    currentParticipantNumber: 25,
    price: 18.0,
    equipments: ["Comfortable shoes"],
    meetingId: "meeting-110"
  },
  // Additional 10 sessions omitted for brevity...
]
